### PR TITLE
Port Retry tests

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
I'm porting the rest of the tests and cannot resolve this error:

image

Any ideas?

### CODE REVIEW

**Comment by marcpiechura** [comment]
Looks like you forgot a () for the KillSwitch

**Comment by vasily-kirichenko** [comment]
Yep, thanks :)

Another question, tests which expect failure like
```csharp
sink.Request(99);
killSwitch.Abort(FailedElement.Exception);
sink.ExpectError().Should().Be(FailedElement.Exception);
```
 fail with
```
Akka.Streams.Contrib.Tests.RetrySpec.Tolerate_killswitch_terminations_after_start

Expected object to be System.Exception with message "cooked failure"
, but found (aggregated) System.Exception with message "cooked failure"
.
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.ObjectAssertions.Be(Object expected, String because, Object[] becauseArgs)
   at Akka.Streams.Contrib.Tests.RetrySpec.Tolerate_killswitch_terminations_after_start() in E:\github\Alpakka\Contrib\src\Akka.Streams.Contrib.Tests\RetrySpec.cs:line 126
```
I think I should use a different assertion.

**Comment by marcpiechura** [comment]
Don’t know if there is a special assertion for it, but I simply used ExpectError().InnerException.Should...

**Comment by vasily-kirichenko** [comment]
I see, thanks.

It's ready, all tests passed.

**Comment by vasily-kirichenko** [comment]
Let me copy the XML docs.

**Comment by vasily-kirichenko** [comment]
Now it's done.

**Comment by marcpiechura** [comment]
LGTM, thanks a lot !

**Pull request merged**
